- hosts: all
  tasks:

    - name: define vars
      set_fact:
         email_text1: ""
      when: email_text1 is not defined

    - name: define vars
      set_fact:
         email_text2: ""
      when: email_text2 is not defined


#         email_text2: "{{ '' if email_text2 is not defined }}"

    - name: send email1 from variables
      shell: 
         cmd:  printf "{{ email_text1 }}"  | mail -s "{{ email_subject }}" {{ email_recipient }}
      when: (email_text1 != "") and (email_recipient is defined)       

    - name: send email2 from variables
      shell: 
        cmd:  printf "{{ email_text2 }}"  | mail -s "{{ email_subject }}" {{ email_recipient }}
      when: (email_text2 != "") and (email_recipient is defined)       



##       cmd:  printf "{{ output1 }} {{ email_text1 }} \n {{ email_text2 }} {{ output2 }}"  | mail -s "{{ email_subject }}" {{ email_recipient }}
