- hosts: all
  name: initial steps for every WF
  gather_facts: no
  vars_files:
    - awx_constants.yml

  tasks:
    - name: prepare sql files
      include_tasks: awx_save_sql_to_file.yml

    - name: show local dirs
      local_action: 
         module: shell
         cmd: "ls -lR /"
      ignore_errors: True

# can use module "synchronize" in case non-exist dest dirs
    - name: copy aux files
      ansible.builtin.copy:
        src:  /runner/project/scripts/remote/run_sql.pl
        dest: /home/porta-one/scripts/run_sql.pl
        mode: preserve
        backup: yes

